library(shiny)
library(shinythemes)
library(DT)

shinyUI(
  navbarPage("Generated by R & Shiny",
             
             tabPanel("Home",
                      h1("This is examples application generated by R & Shiny"),
                      h2("Outline of examples"),
                      p("Used Open data source and show as a Data visualization & Analysis results"),
                      helpText("Program codes on Github and execute through Web Browser")),
             
             tabPanel("Shiny?",
                      h1("Can generate such kind of pages easily"),
                      sidebarLayout(
                        sidebarPanel(
                          sliderInput("bins_shiny",
                                      "Number of bins:",
                                      min = 1,
                                      max = 50,
                                      value = 10)
                        ),
                        mainPanel(
                          plotOutput("distPlot_shiny")
                        )
                      )
             ),
             
             tabPanel("Data visualization", sidebarLayout(
               sidebarPanel(
                 dataSelectUI("plot"),
                 selectInput("select_input_data_for_hist",
                             "Name of colmuns to show:",
                             choices = colnames(iris)),
                 sliderInput("slider_input_data",
                             "Number of bins:",
                             min = 1,
                             max = 50,
                             value = 10),
                 actionButton("trigger_histogram", "Ouput Histgram"),
                 
                 h3("Name of columns for scatter plot:"),
                 selectInput("input_data_for_scatter_plotX",
                             "x-axis",
                             choices = colnames(iris), selected = colnames(iris)[1]),
                 selectInput("input_data_for_scatter_plotY",
                             "y-axis",
                             choices = colnames(iris), selected = colnames(iris)[1]),
                 actionButton("trigger_scatter_plot", "Output Scatter plot")
               ),
               mainPanel(
                 tabsetPanel(type = "tabs",
                             tabPanel("Table",
                                      DT::dataTableOutput("table_for_plot")),
                             tabPanel("Histgarm", plotOutput("histgram")),
                             tabPanel("Scatter plot", plotOutput("scatter_plot", brush = brushOpts(id="plot_brush")),
                                      DT::dataTableOutput("plot_brushedPoints"))
                 )
               )
             )),
             
             tabPanel("Regression", sidebarLayout(
               sidebarPanel(
                 dataSelectUI("regression"),
                 h3("Output result of regression analysis"),
                 selectInput("data_for_regressionY",
                             "Select a objective variable",
                             choices = colnames(iris), selected = colnames(iris)[1]),
                 h3("Selected explanatory variable(s)"),
                 verbatimTextOutput("rows_selected"),
                 selectInput("regression_type",
                             "Method of regression analysis?",
                             choices = c("Multiple regression" = "lm",
                                         "Random forest" = "rf",
                                         "Neural network" = "nnet")),
                 actionButton("regression_button", "Regression")
               ),
               mainPanel(
                 tabsetPanel(type = "tabs",
                             tabPanel("Table", h3("Please select explanatory variable(s)"),
                                      DT::dataTableOutput("data_table_for_regression")),
                             tabPanel("Results", verbatimTextOutput("summary_regression")),
                             tabPanel("See as plots", plotOutput("plot_regression"))
                 )
               )
             )),
             
             tabPanel("classification", sidebarLayout(
               sidebarPanel(
                 dataSelectUI("classification"),
                 h3("Output classification"),
                 selectInput("data_for_classificationY",
                             "Select a objective variable",
                             choices = colnames(iris), selected = colnames(iris)[1]),
                 h3("Selected explanatory variable(s)"),
                 verbatimTextOutput("rows_selected_classification"),
                 selectInput("classification_type",
                             "Method of classification?",
                             choices = c("Random forest" = "rf",
                                         "Neural network" = "nnet")),
                 actionButton("classification_button", "classification")
               ),
               mainPanel(
                 tabsetPanel(type = "tabs",
                             tabPanel("Table", h3("Please select explanatory variable(s)"), 
                                      DT::dataTableOutput("data_table_for_classification")),
                             tabPanel("Results", verbatimTextOutput("summary_classification"))
                 )
               )
             )),
             
             tabPanel("Clustering", sidebarLayout(
               sidebarPanel(
                 dataSelectUI("clustering"),
                 h3("Selected explanatory variable(s)"),
                 verbatimTextOutput("rows_selected_clustering"),
                 numericInput("cluster_number", "Number of cluster?",
                              min = 1, max = 10, value = 1),
                 actionButton("clustering_button", "Clustering")
               ),
               mainPanel(
                 tabsetPanel(type = "tabs",
                             tabPanel("Table", h3("Please select explanatory variable(s)"),
                                      DT::dataTableOutput("data_table_for_clustering")),
                             tabPanel("Results", 
                                      h3("Number of cluster is shown in the left side"),
                                      DT::dataTableOutput("data_with_clustering_result"))
                 )
               )
             )),
             
             navbarMenu("Other",
                        tabPanel("About",
                                 h3("The codes are stored in GitHub: nakajiyo/shiny")
                                 ),
                        tabPanel("Source codes(github)",
                                 h3(a(href="https://github.com/nakajiyo/shiny",
                                   p('https://github.com/nakajiyo/shiny'))),
                                 h3("You can run the codes from R console if put 'runGitHub(nakajiyo/shiny)'")
                                 ),
                        tabPanel("Sepal-Patal",
                                 img(src="https://github.com/nakajiyo/shiny/blob/master/Sepal-petal.jpg", height = 140, width = 180))
                        )
             )
  )